project_name: obfpl
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: obfpl
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - 386
      - amd64
archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Arch "amd64" }}x64-v{{ .Version }}{{- end }}
      {{- if eq .Arch "386" }}x32-v{{ .Version }}{{- end }}
    format: zip
    files:
      - Readme.md
      - LICENCE
      - obfpl.bat
      - profile.yml
      - profile.lua
    wrap_in_directory: true
release:
  prerelease: auto
